### ISSUE TITLE
how to make it run with a source data in a .xlsx or a csv. file

### ISSUE THREAD

**Issue by vanessaling2** [singhj/locality-sensitive-hashing#8]
Hi, 

I have never worked with python. My objective is to make your code work with excel or csv file, as I have some collected twitter messages to be clustered. I have encountered two problems:
1. when i tried to run the example data, there is no output anywhere, the command line finished execution. Then nothing happened. Where can I see the output?
2. I don't know what exactly is the desired data source should look like, from code it looks like some html file. So how exactly can I parse a xlsx file with two columns: twitter id, twitter text?

Thanks!

**Comment by singhj** [comment]
Hi Vanessa, you do have python 2.7.x installed, right?

You want to run serial.py from the command line, like `python serial.py eaxmple_data/Peerbelt.hello.bg.xs.chunked.zip`. This will help you run the example.

Once that is working, you want to change the class `PeerbeltLine` to parse your csv. Given that you don't have html-formatted text, it is safe to remove the calls to BeautifulSoup.

Hope this helps.

**Comment by vanessaling2** [comment]
Hi, 

yes, I did install python 2.7.10. And run exactly as you recommended, but I didn't see any output in the console. Has it been output to somewhere else? Or what should I do additionally to check how the output look like?

Also, I didn't find the class "PeerbeltLine", do you mean this one "peer_belt_driver.py"?

Thanks!

**Comment by tbrooks007** [comment]
Hi Vanessa,

You can use the peer_belt_driver.py code  or read_tweepy.py as examples on how to hook your code into a pipeline to process your tweets from the csv. You should need to write additional code to parse the csv / text file similar to what is is done in the peer_belt_driver.py to parse html files.

Hope this helps, please let us know if it doesn't.

**Comment by liakoyras** [comment]
Hello.
I seem to have the same problem.
I am trying to run the code in the in-memory database using your example data.

I have installed Python 2.7.10.
I have modified `settings.py` in order to select the in-memory database.
When I am trying to run `serial.py` from the command line as following
`py -2 serial.py example_data/Peerbelt.hello.bg.xs.chunked.zip`
although the process is completed without any errors, I can not find the output of that process.

Am I doing something wrong? Is a file created but I cannot find it? Or I am missing the point entirely?

Any help would be much appreciated

**Comment by singhj** [comment]
Hi Ilias Chanis,

This code was working on Google App Engine. The instructions on the [home page](https://github.com/singhj/locality-sensitive-hashing) should still work, though it's possible they have made changes in the platform that are not backward compatible.

If you find that's the case, I'm happy to help make it run in the "upgraded" environment. I suggest trying to run it as-is. And once that works, adapting it to the in-memory database.

Good luck, and if it fails in the AppEngine environment, I'm happy to get it working again in that environment.

Best,

**Comment by liakoyras** [comment]
Thank you for responding singhj.

So, if I understood correctly, there is no way to run the code entirely in your own PC, the only way is by creating a Google App?
Because as stated in your homepage, there is an option to run it using an in-memory database (which i thought it meant that you can run it entirely on your own machine).

Thank you in advance,
