### ISSUE TITLE
question about license

### ISSUE THREAD

**Issue by vanessaling2** [singhj/locality-sensitive-hashing#9]
Hi, I am a little bit confused about the project license. In the homepage http://openlsh.datathinks.org/, it says that this project applies MIT license, but in the license file, it says Apache License V2. Which one is correct? Is it possible to adapt the core lsh code to other language and reference your work? 

Thanks!

**Comment by singhj** [comment]
Hi Vanessa,

Good catch. The license was always intended to be MIT. I have updated the license file accordingly.

What other language were you thinking of? I ask because we did have someone adapt the code to NodeJS about a year ago, if that would help.

All the best, and we'd be happy to lend a hand if you need.

Thanks again,
